server:
  port: 8082

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: vicinia
    password: vicinia
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.vicinia.userservice.messaging
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.vicinia.userservice.messaging.UserEventEnvelope

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
